services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Kematjaya\ItemPack\Service\StockServiceInterface:
        class: Kematjaya\ItemPack\Service\StockService
        
    Kematjaya\ItemPack\Service\StockCardServiceInterface:
        class: Kematjaya\ItemPack\Service\StockCardService
        
    Kematjaya\ItemPack\Service\PriceServiceInterface:
        class: Kematjaya\ItemPack\Service\PriceService
        
    Kematjaya\ItemPack\Service\PriceLogServiceInterface:
        class: Kematjaya\ItemPack\Service\PriceService
        
    Kematjaya\ItemPack\FormSubscriber\ItemEventSubscriber:
        class: Kematjaya\ItemPack\FormSubscriber\ItemEventSubscriber
        
    Kematjaya\ItemPack\FormSubscriber\ItemCategoryEventSubscriber:
        class: Kematjaya\ItemPack\FormSubscriber\ItemCategoryEventSubscriber
        
    Kematjaya\ItemPack\FormSubscriber\ItemPackageFormSubscriber:
        class: Kematjaya\ItemPack\FormSubscriber\ItemPackageFormSubscriber
        
    Kematjaya\ItemPack\Listener\PriceLogListener:
        class: Kematjaya\ItemPack\Listener\PriceLogListener
        tags: 
            - { name: doctrine.event_listener, event: onFlush }
            
    Kematjaya\ItemPack\Fixtures\ItemCategoryFixtures:
        class: Kematjaya\ItemPack\Fixtures\ItemCategoryFixtures
        tags: 
            - doctrine.fixture.orm