services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Kematjaya\ItemPack\Service\StockServiceInterface:
        class: Kematjaya\ItemPack\Service\StockService
        
    Kematjaya\ItemPack\Service\StockCardServiceInterface:
        class: Kematjaya\ItemPack\Service\StockCardService